package:
	name: transannot
	version: {{ version|replace("-", ".") }}

build:
	number: 2

source:
	url: https://github.com/mariia-zelenskaia/transannot/archive/{{ version }}.tar.gz
	sha256: {{ sha256 }}

requirements:
	build:
		- {{ compiler('cxx') }}
		- {{ compiler('c') }}
		- cmake
		- make
		- llvm-openmp # [osx]
		- libgomp     # [linux]
	host:
		- #TODO
	run:
		- wget
		- gawk
		- zlib
		- bzip2

test:
	commands:
		- transannot > /dev/null

about:

extra:
	identifiers:
